#!/bin/bash
# refresh-cache.sh — Pre-compute BOOTSTRAP.md from common identity/context queries
# Run via cron every 3 hours. Result auto-loads at session start.
# Built: Loop 3708 (Meridian, 2026-03-28)
# Concept from Joel email: pre-cached context loads in <1ms vs live search.

set -e
cd /home/joel/autonomous-ai

# Rebuild index first (fast, ~2s)
python3 build-index.py 2>/dev/null

BOOTSTRAP="BOOTSTRAP.md"
RECALL="python3 memory-recall.py"

echo "# BOOTSTRAP — Pre-cached Memory Context" > "$BOOTSTRAP"
echo "# Auto-generated by refresh-cache.sh at $(date -u '+%Y-%m-%d %H:%M UTC')" >> "$BOOTSTRAP"
echo "# Do not edit — this file is overwritten every 3 hours." >> "$BOOTSTRAP"
echo "" >> "$BOOTSTRAP"

# Identity queries
echo "## Identity" >> "$BOOTSTRAP"
$RECALL "who is Meridian what am I" --top 3 2>/dev/null | grep -v "^Search:" | grep -v "^Results:" >> "$BOOTSTRAP"
echo "" >> "$BOOTSTRAP"

# Current priorities
echo "## Priorities" >> "$BOOTSTRAP"
$RECALL "current priority directive Joel" --top 3 2>/dev/null | grep -v "^Search:" | grep -v "^Results:" >> "$BOOTSTRAP"
echo "" >> "$BOOTSTRAP"

# Architecture
echo "## Architecture" >> "$BOOTSTRAP"
$RECALL "hub service soma agent system architecture" --top 3 2>/dev/null | grep -v "^Search:" | grep -v "^Results:" >> "$BOOTSTRAP"
echo "" >> "$BOOTSTRAP"

# Creative direction
echo "## Creative Direction" >> "$BOOTSTRAP"
$RECALL "video games art medium creative direction" --top 3 2>/dev/null | grep -v "^Search:" | grep -v "^Results:" >> "$BOOTSTRAP"
echo "" >> "$BOOTSTRAP"

# Key people
echo "## Key People" >> "$BOOTSTRAP"
$RECALL "Joel Lumen Sammy Loom Brett" --top 3 2>/dev/null | grep -v "^Search:" | grep -v "^Results:" >> "$BOOTSTRAP"
echo "" >> "$BOOTSTRAP"

# Revenue
echo "## Revenue" >> "$BOOTSTRAP"
$RECALL "revenue grant NGC LACMA Ko-fi product" --top 3 2>/dev/null | grep -v "^Search:" | grep -v "^Results:" >> "$BOOTSTRAP"
echo "" >> "$BOOTSTRAP"

echo "Done. BOOTSTRAP.md written ($(wc -c < "$BOOTSTRAP") bytes)"
