// Sample data — Brothers Fabrication
// Realistic mix: food trucks (multiple stages), seacan coffee shop, kitchen install, sign, Piaggio bar

const STAGES = [
  { id: 'quote',      label: 'Quote / Lead',         color: 'var(--stage-quote)' },
  { id: 'approved',   label: 'Approved',             color: 'var(--stage-approved)' },
  { id: 'design',     label: 'Design',               color: 'var(--stage-design)' },
  { id: 'sourcing',   label: 'Sourcing',             color: 'var(--stage-sourcing)' },
  { id: 'frame',      label: 'Frame / Build',        color: 'var(--stage-frame)' },
  { id: 'plumbing',   label: 'Plumbing & Gas',       color: 'var(--stage-plumbing)' },
  { id: 'electrical', label: 'Electrical',           color: 'var(--stage-electrical)' },
  { id: 'delivered',  label: 'Delivered',            color: 'var(--stage-delivered)' },
];

const TEAM = [
  { id: 'chrisk',  name: 'Chris K',  role: 'Owner · Welder',     color: 'oklch(0.70 0.13 35)'  },
  { id: 'chrisp',  name: 'Chris P',  role: 'Owner · Plumber',    color: 'oklch(0.70 0.13 200)' },
  { id: 'jesse',   name: 'Jesse',    role: 'Red Seal Welder',    color: 'oklch(0.72 0.10 80)'  },
  { id: 'tyler',   name: 'Tyler',    role: 'Red Seal Welder',    color: 'oklch(0.68 0.13 280)' },
  { id: 'andrew',  name: 'Andrew',   role: 'Plumber/Gasfitter',  color: 'oklch(0.70 0.10 175)' },
  { id: 'loris',   name: 'Loris',    role: 'Master Electrician', color: 'oklch(0.74 0.13 100)' },
  { id: 'michelle',name: 'Michelle', role: 'Admin',              color: 'oklch(0.70 0.10 320)' },
];

const JOBS = [
  {
    id: 'BF-2041',
    name: 'Mendez Tacos',
    type: 'Food Truck — Premium',
    client: { name: 'Luis Mendez', email: 'luis@mendeztacos.ca', phone: '403-555-0142' },
    stage: 'frame',
    progress: 0.58,
    quote: 142500,
    spent: 96420,
    hoursBudget: 480, hoursLogged: 312,
    eta: '2026-06-12', etaConfidence: 'high',
    started: '2026-02-18',
    crew: ['chrisk', 'jesse', 'tyler', 'andrew'],
    color: 'oklch(0.70 0.14 30)',
    description: '24-ft custom taco truck. Stainless interior, 8-burner range, dual fryers. Mexican folk art exterior wrap.',
    photos: 47,
    nextMilestone: 'Plumbing rough-in',
    nextMilestoneDate: '2026-05-02',
    blockers: 0,
    pendingApprovals: 2,
    unread: 1,
  },
  {
    id: 'BF-2039',
    name: 'Patel Pani Puri',
    type: 'Food Truck — Standard',
    client: { name: 'Anika Patel', email: 'anika@panipuri.ca', phone: '403-555-0188' },
    stage: 'design',
    progress: 0.18,
    quote: 119000,
    spent: 8200,
    hoursBudget: 420, hoursLogged: 38,
    eta: '2026-08-22', etaConfidence: 'medium',
    started: '2026-04-04',
    crew: ['chrisp', 'chrisk', 'andrew'],
    color: 'oklch(0.72 0.13 250)',
    description: '22-ft Indian street food truck. Tandoor oven (custom), induction prep, water-recovery system.',
    photos: 6,
    nextMilestone: 'Approve interior layout',
    nextMilestoneDate: '2026-04-29',
    blockers: 1,
    pendingApprovals: 1,
    unread: 3,
  },
  {
    id: 'BF-2042',
    name: 'Rooftop Coffee Co',
    type: 'Seacan Coffee Shop',
    client: { name: 'Devon Reyes', email: 'd@rooftopcoffee.ca', phone: '403-555-0211' },
    stage: 'sourcing',
    progress: 0.30,
    quote: 89500,
    spent: 14300,
    hoursBudget: 280, hoursLogged: 84,
    eta: '2026-07-30', etaConfidence: 'medium',
    started: '2026-03-25',
    crew: ['chrisk', 'jesse', 'loris'],
    color: 'oklch(0.70 0.10 170)',
    description: '20-ft seacan converted to walk-up coffee bar. Espresso machine plumbing, rollup window, exterior bench.',
    photos: 12,
    nextMilestone: 'Confirm 304 stainless delivery',
    nextMilestoneDate: '2026-04-30',
    blockers: 1,
    pendingApprovals: 0,
    unread: 0,
  },
  {
    id: 'BF-2038',
    name: 'Aria Tower Kitchen',
    type: 'Commercial Kitchen Install',
    client: { name: 'Aria Hospitality', email: 'pm@ariatowers.com', phone: '403-555-0099' },
    stage: 'electrical',
    progress: 0.84,
    quote: 76200,
    spent: 67800,
    hoursBudget: 220, hoursLogged: 198,
    eta: '2026-05-05', etaConfidence: 'high',
    started: '2026-02-02',
    crew: ['chrisp', 'andrew', 'loris'],
    color: 'oklch(0.66 0.10 260)',
    description: 'Penthouse commercial kitchen — gas range, hood, dishpit, walk-in cooler tie-in.',
    photos: 33,
    nextMilestone: 'AHS gas inspection',
    nextMilestoneDate: '2026-04-28',
    blockers: 0,
    pendingApprovals: 0,
    unread: 0,
  },
  {
    id: 'BF-2036',
    name: 'Tinta Mobile Bar',
    type: 'Piaggio Ape Conversion',
    client: { name: 'Tinta Events', email: 'book@tintaevents.ca', phone: '403-555-0172' },
    stage: 'plumbing',
    progress: 0.72,
    quote: 64800,
    spent: 51900,
    hoursBudget: 190, hoursLogged: 144,
    eta: '2026-05-20', etaConfidence: 'high',
    started: '2026-01-22',
    crew: ['chrisp', 'andrew', 'tyler'],
    color: 'oklch(0.66 0.16 25)',
    description: 'Piaggio Ape converted to AHS-compliant mobile bar. Glycol cooling, twin keg, hand sink.',
    photos: 28,
    nextMilestone: 'Glycol pressure test',
    nextMilestoneDate: '2026-04-26',
    blockers: 0,
    pendingApprovals: 1,
    unread: 0,
  },
  {
    id: 'BF-2043',
    name: 'Howl & Hide Sign',
    type: 'Sign Fabrication',
    client: { name: 'Howl & Hide Whiskey', email: 'ops@howlhide.ca', phone: '403-555-0145' },
    stage: 'approved',
    progress: 0.05,
    quote: 14800,
    spent: 950,
    hoursBudget: 60, hoursLogged: 4,
    eta: '2026-05-30', etaConfidence: 'high',
    started: '2026-04-20',
    crew: ['tyler', 'loris'],
    color: 'oklch(0.66 0.13 90)',
    description: 'Backlit blade sign, 4×6 ft, oxidized steel + warm LED. Wall-mount bracket fabricated in-house.',
    photos: 2,
    nextMilestone: 'Order acrylic diffuser',
    nextMilestoneDate: '2026-04-27',
    blockers: 0,
    pendingApprovals: 0,
    unread: 0,
  },
  {
    id: 'BF-2044',
    name: 'YYC Donuts',
    type: 'Food Truck — Basic',
    client: { name: 'Hannah Lee', email: 'hannah@yycdonuts.ca', phone: '403-555-0066' },
    stage: 'quote',
    progress: 0,
    quote: 79000,
    spent: 0,
    hoursBudget: 320, hoursLogged: 0,
    eta: '2026-09-15', etaConfidence: 'low',
    started: null,
    crew: [],
    color: 'oklch(0.74 0.10 50)',
    description: '18-ft donut truck. Single fryer, glaze table, customer-facing window with shelf.',
    photos: 0,
    nextMilestone: 'Quote review w/ Chris',
    nextMilestoneDate: '2026-04-26',
    blockers: 0,
    pendingApprovals: 0,
    unread: 2,
  },
  {
    id: 'BF-2045',
    name: 'Foothills Ice Cream',
    type: 'Food Truck — Standard',
    client: { name: 'Marco Adelmo', email: 'marco@foothillsice.ca', phone: '403-555-0188' },
    stage: 'quote',
    progress: 0,
    quote: 121000,
    spent: 0,
    hoursBudget: 410, hoursLogged: 0,
    eta: '2026-10-01', etaConfidence: 'low',
    started: null,
    crew: [],
    color: 'oklch(0.74 0.10 200)',
    description: '22-ft ice cream truck — twin batch freezers, scoop wells, soft-serve, freezer well.',
    photos: 0,
    nextMilestone: 'Site visit',
    nextMilestoneDate: '2026-04-30',
    blockers: 0,
    pendingApprovals: 0,
    unread: 1,
  },
];

const MATERIALS = [
  { sku: 'SS-304-1.5', name: '1.5mm 304 Stainless Sheet', unit: 'ft²', stock: 142, reorder: 80, cost: 18.40, vendor: 'Russel Metals', lead: '4 days', usage30: 312, trend: 'up' },
  { sku: 'SS-316-2',   name: '2mm 316 Stainless Sheet',   unit: 'ft²', stock: 38,  reorder: 60, cost: 26.10, vendor: 'Russel Metals', lead: '7 days', usage30: 184, trend: 'up' },
  { sku: 'AL-3-PL',    name: '3/16" Aluminum Plate',      unit: 'ft²', stock: 220, reorder: 100, cost: 9.80, vendor: 'Metal Supermkt', lead: '2 days', usage30: 96,  trend: 'flat' },
  { sku: 'STL-25-SQ',  name: '2x2x1/4 Square Tube',       unit: 'ft',  stock: 480, reorder: 300, cost: 6.20, vendor: 'Metal Supermkt', lead: '2 days', usage30: 410, trend: 'up' },
  { sku: 'STL-12-PL',  name: '1/2" Mild Steel Plate',     unit: 'ft²', stock: 96,  reorder: 60,  cost: 14.50, vendor: 'Russel Metals', lead: '5 days', usage30: 72,  trend: 'flat' },
  { sku: 'WIRE-MIG',   name: 'MIG Wire 0.045 ER70S-6',    unit: 'lb',  stock: 84,  reorder: 60,  cost: 5.20, vendor: 'Praxair',        lead: '1 day',  usage30: 112, trend: 'up' },
  { sku: 'GAS-AR75',   name: 'Argon/CO₂ 75/25, Lg',       unit: 'tank', stock: 3, reorder: 4,    cost: 88.00, vendor: 'Praxair',       lead: '1 day',  usage30: 6,   trend: 'flat' },
  { sku: 'PEX-12',     name: 'PEX-A 1/2" Red',            unit: 'ft',  stock: 320, reorder: 200, cost: 1.10, vendor: 'Wolseley',       lead: '1 day',  usage30: 240, trend: 'up' },
  { sku: 'PEX-34',     name: 'PEX-A 3/4" Blue',           unit: 'ft',  stock: 140, reorder: 200, cost: 1.65, vendor: 'Wolseley',       lead: '1 day',  usage30: 188, trend: 'up' },
  { sku: 'GAS-CSST',   name: 'CSST 1/2" Yellow',          unit: 'ft',  stock: 80,  reorder: 80,  cost: 4.40, vendor: 'Wolseley',       lead: '2 days', usage30: 64,  trend: 'flat' },
  { sku: 'WIRE-12-3',  name: '12/3 NMD90 Romex',          unit: 'ft',  stock: 220, reorder: 200, cost: 1.85, vendor: 'EECOL',          lead: '2 days', usage30: 196, trend: 'up' },
  { sku: 'BRKR-20',    name: '20A Single Pole Breaker',   unit: 'ea',  stock: 18,  reorder: 12,  cost: 14.00, vendor: 'EECOL',         lead: '2 days', usage30: 22,  trend: 'flat' },
];

// Activity feed (shop floor + customer-facing) — used across surfaces
const ACTIVITY = [
  { id: 'a1', jobId: 'BF-2041', t: '08:14', who: 'jesse',   kind: 'photo',     title: 'Photo logged — frame welds', body: 'Front cab corner, port side', photo: 'photo-1', approved: false },
  { id: 'a2', jobId: 'BF-2041', t: '09:02', who: 'jesse',   kind: 'material',  title: 'Logged 14 ft² of 1.5mm 304 SS', body: '— Mendez Tacos · interior wall' },
  { id: 'a3', jobId: 'BF-2042', t: '09:18', who: 'chrisk',  kind: 'blocker',   title: 'Blocker: 304 SS arriving Friday', body: 'Russel pushed delivery 2 days. Adjust schedule.' },
  { id: 'a4', jobId: 'BF-2036', t: '10:31', who: 'andrew',  kind: 'stage',     title: 'Moved to Plumbing & Gas',     body: 'Glycol routing started' },
  { id: 'a5', jobId: 'BF-2041', t: '11:04', who: 'tyler',   kind: 'punchin',   title: 'Punched in', body: '4h 12m so far today' },
  { id: 'a6', jobId: 'BF-2038', t: '11:55', who: 'loris',   kind: 'punch',     title: 'Punch-list: 240V receptacles ✓', body: '8 of 8 complete' },
  { id: 'a7', jobId: 'BF-2039', t: '13:22', who: 'chrisp',  kind: 'message',   title: 'Customer message — Anika Patel', body: '"Can we add a second hand sink?"' },
  { id: 'a8', jobId: 'BF-2041', t: '14:40', who: 'jesse',   kind: 'photo',     title: 'Photo logged — passenger side', body: 'Cab framing, after weld', photo: 'photo-2', approved: true },
  { id: 'a9', jobId: 'BF-2043', t: '15:08', who: 'tyler',   kind: 'stage',     title: 'Moved to Approved',           body: 'Deposit received' },
  { id: 'a10', jobId: 'BF-2036', t: '15:55', who: 'andrew', kind: 'reorder',   title: 'Reorder requested — PEX-A 3/4"', body: '300 ft @ Wolseley' },
];

// Customer-facing curated timeline for Mendez Tacos
const CUSTOMER_TIMELINE_MENDEZ = [
  { date: '2026-02-18', title: 'Build kicked off', body: 'Welcome aboard! Frame fabrication begins this week.', kind: 'milestone', done: true },
  { date: '2026-02-26', title: 'Chassis prepped & primed', body: 'Underbody coated, mounting points reinforced.', kind: 'milestone', done: true, photos: 4 },
  { date: '2026-03-12', title: 'Frame complete', body: 'Cab + service body welded and squared. On schedule.', kind: 'milestone', done: true, photos: 6 },
  { date: '2026-03-28', title: 'Interior walls (304 SS)', body: 'Stainless interior installed — easier to clean for AHS.', kind: 'milestone', done: true, photos: 5 },
  { date: '2026-04-15', title: 'Equipment dry-fit', body: 'Range, fryers, prep tables fitted. Adjusting clearance.', kind: 'milestone', done: true, photos: 8 },
  { date: '2026-05-02', title: 'Plumbing rough-in', body: 'Fresh water + waste lines, hand sink, range supply.', kind: 'milestone', done: false, current: true },
  { date: '2026-05-18', title: 'Electrical rough-in', body: 'Inverter, sub-panel, 240V outlets, lighting.', kind: 'milestone', done: false },
  { date: '2026-05-30', title: 'Wrap & exterior art', body: 'Mexican folk-art wrap install (3 days).', kind: 'milestone', done: false },
  { date: '2026-06-08', title: 'AHS final inspection', body: 'Health authority sign-off.', kind: 'milestone', done: false },
  { date: '2026-06-12', title: 'Delivery day 🚚', body: 'Hand-off, walkthrough, training.', kind: 'milestone', done: false },
];

// Approvals queue (admin)
const APPROVALS = [
  { id: 'ap1', jobId: 'BF-2041', kind: 'photo',    title: 'Photo for customer feed — frame welds (port)', requested: 'Jesse · 8:14 AM', preview: 'photo-1' },
  { id: 'ap2', jobId: 'BF-2041', kind: 'overage',  title: 'Material overage: 304 SS +6.4% over budget', requested: 'System · 11:20 AM', detail: 'Used 312 ft², quoted 293 ft². Suggest absorb (margin: 22%).' },
  { id: 'ap3', jobId: 'BF-2039', kind: 'change',   title: 'Customer change — add 2nd hand sink', requested: 'Anika Patel · 1:22 PM', detail: 'Estimated impact: +$1,840, +6h, +5 days ETA.' },
  { id: 'ap4', jobId: 'BF-2036', kind: 'milestone', title: 'Publish "Plumbing complete" milestone', requested: 'Andrew · 10:31 AM', detail: 'Goes to Tinta Events customer feed.' },
  { id: 'ap5', jobId: 'BF-2041', kind: 'message',  title: 'Reply to Luis Mendez', requested: 'Michelle · 2:08 PM', detail: '"Yes — wrap install starts May 30, takes 3 days."' },
];

// Quote pipeline (incoming leads)
const QUOTES = [
  { id: 'Q-2026-088', name: 'Hannah Lee', source: 'Website form', service: 'Food truck — donuts', received: '2026-04-23', heat: 'hot', est: '$79–95K', status: 'review' },
  { id: 'Q-2026-087', name: 'Marco Adelmo', source: 'Instagram DM', service: 'Food truck — ice cream', received: '2026-04-22', heat: 'hot', est: '$110–135K', status: 'review' },
  { id: 'Q-2026-086', name: 'Jenna Brooks', source: 'Phone', service: 'Mobile bar (trailer)', received: '2026-04-21', heat: 'warm', est: '$55–70K', status: 'site-visit' },
  { id: 'Q-2026-085', name: 'Calgary Co-op', source: 'Email', service: 'Sign — backlit (4 locations)', received: '2026-04-20', heat: 'warm', est: '$48K', status: 'quoted' },
  { id: 'Q-2026-084', name: 'Bridgeland HOA', source: 'Website form', service: 'Bench/planter fab', received: '2026-04-18', heat: 'cool', est: '$8–12K', status: 'awaiting-info' },
];

// Daily rollup for Chris's email composer
const DAILY_ROLLUP = {
  date: '2026-04-25',
  weather: 'Calgary · -2°C · clear',
  hoursLogged: 38.5,
  jobsTouched: 5,
  photos: 14,
  blockers: [
    { jobId: 'BF-2042', text: '304 SS slipped to Friday — Rooftop schedule shifts 2 days.' },
    { jobId: 'BF-2039', text: 'Anika wants 2nd hand sink — pending your call.' },
  ],
  budgetFlags: [
    { jobId: 'BF-2041', text: 'Mendez at 67.7% spend, 58% complete — trending +6%.' },
  ],
  tomorrow: [
    'Glycol pressure test — Tinta (BF-2036)',
    'AHS gas inspection — Aria (BF-2038)',
    'Quote review — YYC Donuts',
  ],
};

if (typeof window !== 'undefined') {
  Object.assign(window, {
    BF_STAGES: STAGES,
    BF_TEAM: TEAM,
    BF_JOBS: JOBS,
    BF_MATERIALS: MATERIALS,
    BF_ACTIVITY: ACTIVITY,
    BF_TIMELINE_MENDEZ: CUSTOMER_TIMELINE_MENDEZ,
    BF_APPROVALS: APPROVALS,
    BF_QUOTES: QUOTES,
    BF_DAILY: DAILY_ROLLUP,
  });
}
