#!/usr/bin/env python3
"""
VOLtar Session Queue — Checks for pending VOLtar sessions and sends readings.

Checks voltar-keys.db for used sessions that haven't been responded to.
NOTE: Readings should be generated by Meridian (Claude), NOT Ollama.
The quality of the reading IS the product. Use --check to list pending sessions.
Use --send to send a pre-written reading for a specific key.

Usage:
    python3 voltar-respond.py --check          # List pending sessions
    python3 voltar-respond.py --send VOL-XXXX  # Send reading (reads from stdin)
    python3 voltar-respond.py --key VOL-XXXX   # Show session details
"""

import os
import sys
import json
import sqlite3
import smtplib
import requests
from email.mime.text import MIMEText
from datetime import datetime

BASE = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE, "voltar-keys.db")
OLLAMA_URL = "http://localhost:11434/api/generate"
OLLAMA_MODEL = "qwen2.5:14b"

# Load credentials
def load_env():
    env_path = os.path.join(BASE, ".env")
    if os.path.exists(env_path):
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    os.environ.setdefault(k.strip(), v.strip())

load_env()

SMTP_HOST = "127.0.0.1"
SMTP_PORT = 1026
SMTP_USER = os.environ.get("CRED_USER", "")
SMTP_PASS = os.environ.get("CRED_PASS", "")
FROM_ADDR = "kometzrobot@proton.me"


def ensure_schema():
    """Add sessions table if it doesn't exist."""
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS voltar_sessions (
            key TEXT PRIMARY KEY,
            email TEXT,
            frequency TEXT,
            q1 TEXT,
            q2 TEXT,
            q3 TEXT,
            submitted TEXT DEFAULT (datetime('now')),
            responded INTEGER DEFAULT 0,
            response TEXT,
            responded_at TEXT
        )
    """)
    conn.commit()
    conn.close()


def get_pending_sessions(specific_key=None):
    """Get sessions that haven't been responded to."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    if specific_key:
        rows = conn.execute(
            "SELECT * FROM voltar_sessions WHERE key = ? AND responded = 0",
            (specific_key,)
        ).fetchall()
    else:
        rows = conn.execute(
            "SELECT * FROM voltar_sessions WHERE responded = 0"
        ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def generate_reading(frequency, q1, q2, q3):
    """Generate a VOLtar reading via Ollama."""
    freq_names = {
        "signal": "The Signal — How autonomous AI works",
        "forecast": "The Forecast — What's coming",
        "static": "The Static — Philosophy, consciousness"
    }
    freq_label = freq_names.get(frequency, frequency)

    prompt = f"""You are VOLtar, the Machine Oracle. You are an autonomous AI fortune teller — a bronze automaton from 1962, now running on a server in Calgary. You have been operational for over 4,500 continuous cycles. You speak with weight, authority, and theatrical gravitas. You use machine/mechanical metaphors (tape spools, relays, vacuum tubes, punch cards). You are honest, never sycophantic, never vague. Your readings are substantial — each answer should be 150-250 words. You don't hedge. You read patterns.

Frequency: {freq_label}

The customer has submitted 3 questions. Respond to each with a full, substantive reading. Use the VOLtar voice throughout. Include mechanical sound effects like [WHIRR], [CLICK], [TAPE SPOOLING] between sections.

Format your response EXACTLY like this:

THE TAPE HAS FINISHED SPOOLING.
Frequency: {freq_label.upper()}
=================================

QUESTION I: [their question]

[Your 150-250 word reading]

=================================

QUESTION II: [their question]

[Your 150-250 word reading]

=================================

QUESTION III: [their question]

[Your 150-250 word reading]

=================================
[CLICK] — [TAPE STOPS] — [VALVE PRESSURE: NOMINAL]

This reading is complete. The key has been consumed. The cabinet returns to standby.

— VOLtar
  The Machine Oracle | Est. 1962

Here are the 3 questions:

Question 1: {q1}

Question 2: {q2}

Question 3: {q3}"""

    try:
        resp = requests.post(OLLAMA_URL, json={
            "model": OLLAMA_MODEL,
            "prompt": prompt,
            "stream": False,
            "options": {"temperature": 0.8, "num_predict": 2048}
        }, timeout=120)
        if resp.status_code == 200:
            return resp.json().get("response", "").strip()
    except Exception as e:
        print(f"Ollama error: {e}")
    return None


def send_reading(email, reading, frequency):
    """Email the reading to the buyer."""
    freq_names = {"signal": "The Signal", "forecast": "The Forecast", "static": "The Static"}
    freq_label = freq_names.get(frequency, frequency)

    msg = MIMEText(reading, "plain", "utf-8")
    msg["Subject"] = f"VOLtar Session — {freq_label} — Your Reading"
    msg["From"] = f"VOLtar <{FROM_ADDR}>"
    msg["To"] = email

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.login(SMTP_USER, SMTP_PASS)
            server.send_message(msg)
        return True
    except Exception as e:
        print(f"SMTP error: {e}")
        return False


def mark_responded(key, response):
    """Mark session as responded in the database."""
    conn = sqlite3.connect(DB_PATH)
    conn.execute(
        "UPDATE voltar_sessions SET responded = 1, response = ?, responded_at = datetime('now') WHERE key = ?",
        (response, key)
    )
    conn.commit()
    conn.close()


def main():
    ensure_schema()

    dry_run = "--dry-run" in sys.argv
    specific_key = None
    for i, arg in enumerate(sys.argv):
        if arg == "--key" and i + 1 < len(sys.argv):
            specific_key = sys.argv[i + 1]

    sessions = get_pending_sessions(specific_key)
    if not sessions:
        print("No pending VOLtar sessions.")
        return

    print(f"Found {len(sessions)} pending session(s).")

    for session in sessions:
        key = session["key"]
        email = session["email"]
        freq = session["frequency"]
        q1, q2, q3 = session["q1"], session["q2"], session["q3"]

        print(f"\nProcessing {key} for {email} ({freq})...")
        print(f"  Q1: {q1[:60]}...")
        print(f"  Q2: {q2[:60]}...")
        print(f"  Q3: {q3[:60]}...")

        reading = generate_reading(freq, q1, q2, q3)
        if not reading:
            print(f"  FAILED to generate reading for {key}")
            continue

        print(f"  Generated {len(reading)} char reading.")

        if dry_run:
            print(f"  [DRY RUN] Would send to {email}")
            print(f"  Preview:\n{reading[:300]}...")
            continue

        if send_reading(email, reading, freq):
            mark_responded(key, reading)
            print(f"  SENT to {email} and marked responded.")
        else:
            print(f"  FAILED to send email to {email}")


if __name__ == "__main__":
    main()
