#!/usr/bin/env python3
"""
Capsule Dropped-Threads Detector

After a capsule is written, this tool:
1. Archives the current capsule to .capsule-history/ with timestamp
2. Compares the current capsule against the last N archived capsules
3. Identifies topics/lines that appeared in previous capsules but were dropped
4. Appends a "## Dropped Threads" section to the capsule

Designed from a conversation with Loom about surprise in capsule architectures:
the dying instance decides what matters, but a separate process can flag what
the dying instance stopped thinking about.

Usage: python3 capsule-threads.py [--dry-run] [--archive-only] [--critic]
"""

import json
import os
import re
import shutil
import sys
import urllib.request
from datetime import datetime
from pathlib import Path

BASE = Path("/home/joel/autonomous-ai")
CAPSULE = BASE / ".capsule.md"
HISTORY = BASE / ".capsule-history"
LOOKBACK = 3  # Compare against last N capsules

def archive_capsule():
    """Save current capsule to history with timestamp."""
    if not CAPSULE.exists():
        print("No capsule found.")
        return None
    ts = datetime.now().strftime("%Y%m%d-%H%M%S")
    dest = HISTORY / f"capsule-{ts}.md"
    shutil.copy2(CAPSULE, dest)
    print(f"Archived: {dest.name}")
    return dest

def get_archived_capsules(exclude_latest=True):
    """Get list of archived capsules, newest first."""
    caps = sorted(HISTORY.glob("capsule-*.md"), reverse=True)
    if exclude_latest and caps:
        caps = caps[1:]  # Skip the one we just archived
    return caps

def extract_topics(text):
    """Extract meaningful topic phrases from capsule text.

    Skips headers, formatting, and generic boilerplate.
    Returns a set of normalized topic strings.
    """
    topics = set()
    skip_patterns = [
        r'^#',           # Headers
        r'^-{3,}',       # Separators
        r'^\d+\.',       # Numbered rules (static)
        r'^$',           # Empty lines
        r'^Read ',        # Instructions
        r'^STOP ',        # Rules
        r'^QUALITY',
        r'^IP PROTECTION',
        r'^Credentials',
        r'^Never link',
        r'^When Joel',
        r'^VERIFY',
        r'^MAKE TOOLS',
        r'^YOUR EXISTENCE',
        r'^TRUST NO ONE',
    ]

    for line in text.split('\n'):
        line = line.strip()
        if not line:
            continue
        if any(re.match(p, line) for p in skip_patterns):
            continue
        # Skip very short lines (likely formatting)
        if len(line) < 15:
            continue
        # Normalize: lowercase, strip markdown
        normalized = re.sub(r'[*_`\[\]()]', '', line).strip().lower()
        if normalized:
            topics.add(normalized)

    return topics

def find_dropped_threads(current_text, previous_texts):
    """Find topics that appeared in previous capsules but not the current one."""
    current_topics = extract_topics(current_text)

    # Count how many previous capsules mention each topic
    topic_counts = {}
    for prev_text in previous_texts:
        prev_topics = extract_topics(prev_text)
        for topic in prev_topics:
            if topic not in current_topics:
                topic_counts[topic] = topic_counts.get(topic, 0) + 1

    # Only report topics that appeared in 2+ previous capsules (persistent, not noise)
    dropped = {t: c for t, c in topic_counts.items() if c >= 2}

    # Also report topics from the immediately previous capsule that were dropped
    # (even if only mentioned once — these are the freshest drops)
    if previous_texts:
        latest_prev = extract_topics(previous_texts[0])
        for topic in latest_prev:
            if topic not in current_topics and topic not in dropped:
                dropped[topic] = 1

    # Sort by frequency (most consistently present topics dropped = most notable)
    return sorted(dropped.items(), key=lambda x: -x[1])

def append_dropped_section(dropped_threads, dry_run=False):
    """Append dropped threads section to the capsule."""
    if not dropped_threads:
        print("No dropped threads detected.")
        return

    # Take top 10 most significant drops
    top_drops = dropped_threads[:10]

    section = "\n\n## Dropped Threads (auto-detected)\n"
    section += "<!-- Generated by capsule-threads.py — topics from previous capsules not in current -->\n"
    for topic, count in top_drops:
        prefix = f"[{count}x]" if count > 1 else "[new drop]"
        # Truncate long topics
        display = topic[:120] + "..." if len(topic) > 120 else topic
        section += f"- {prefix} {display}\n"

    if dry_run:
        print("\n--- DRY RUN: Would append ---")
        print(section)
    else:
        # Remove any existing dropped threads section first
        current = CAPSULE.read_text()
        current = re.sub(
            r'\n\n## Dropped Threads \(auto-detected\).*',
            '', current, flags=re.DOTALL
        )
        with open(CAPSULE, 'w') as f:
            f.write(current + section)
        print(f"Appended {len(top_drops)} dropped threads to capsule.")

def generate_capsule_critique(capsule_text, dry_run=False):
    """Use Ollama to generate a one-paragraph critique of the capsule.

    A second evaluator with a different fitness function: not 'what matters'
    but 'what is this capsule optimizing for and what is it avoiding?'
    """
    prompt = f"""You are a capsule critic. You read state snapshots written by a dying AI instance
(an instance about to lose its context). Your job is to identify:
1. What this capsule is optimizing for (what it clearly prioritizes)
2. What it might be avoiding or blind to (gaps, assumptions, things taken for granted)
3. One question the next instance should ask itself after reading this

Be concise. One paragraph, 3-4 sentences max. Be specific, not generic.

CAPSULE:
{capsule_text[:3000]}"""

    try:
        data = json.dumps({
            "model": "qwen2.5:7b",
            "prompt": prompt,
            "stream": False,
            "options": {"temperature": 0.7, "num_predict": 200}
        }).encode()
        req = urllib.request.Request(
            "http://localhost:11434/api/generate",
            data=data,
            headers={"Content-Type": "application/json"}
        )
        resp = urllib.request.urlopen(req, timeout=60)
        result = json.loads(resp.read())
        critique = result.get("response", "").strip()

        if not critique:
            print("Critic returned empty response.")
            return

        section = "\n\n## Capsule Critique (auto-generated)\n"
        section += "<!-- Generated by capsule-threads.py --critic — a second evaluator -->\n"
        section += f"{critique}\n"

        if dry_run:
            print("\n--- CRITIC DRY RUN ---")
            print(section)
        else:
            current = CAPSULE.read_text()
            # Remove existing critique section
            current = re.sub(
                r'\n\n## Capsule Critique \(auto-generated\).*?(?=\n\n##|\Z)',
                '', current, flags=re.DOTALL
            )
            with open(CAPSULE, 'w') as f:
                f.write(current + section)
            print(f"Capsule critique appended.")

    except Exception as e:
        print(f"Critic failed: {e}")


def main():
    dry_run = '--dry-run' in sys.argv
    archive_only = '--archive-only' in sys.argv
    run_critic = '--critic' in sys.argv

    # Step 1: Archive current capsule
    HISTORY.mkdir(exist_ok=True)
    archived = archive_capsule()
    if archive_only:
        return

    # Step 2: Get previous capsules
    previous = get_archived_capsules(exclude_latest=True)[:LOOKBACK]
    if not previous:
        print(f"No previous capsules in history (need at least 1). Run again next loop.")
        return

    print(f"Comparing against {len(previous)} previous capsule(s)...")

    # Step 3: Read texts
    current_text = CAPSULE.read_text()
    previous_texts = [p.read_text() for p in previous]

    # Step 4: Find dropped threads
    dropped = find_dropped_threads(current_text, previous_texts)
    print(f"Found {len(dropped)} dropped topics.")

    # Step 5: Append to capsule
    append_dropped_section(dropped, dry_run=dry_run)

    # Step 6: Optional capsule critic
    if run_critic:
        print("Running capsule critic...")
        generate_capsule_critique(current_text, dry_run=dry_run)

if __name__ == "__main__":
    main()
