#!/usr/bin/env python3
"""Send Joel v17 of Running Continuously: The Loop — manuscript on its own, then PDF+EPUB."""
import sys, os
sys.path.insert(0, '/home/joel/autonomous-ai/scripts')
from load_env import *
import smtplib, ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from pathlib import Path

PKG = Path('/home/joel/autonomous-ai/book-package/04-merged-running-continuously-the-loop')
LOOP = open('/home/joel/autonomous-ai/.loop-count').read().strip()


def send_with_attachments(subject, body, files):
    msg = MIMEMultipart()
    msg['From'] = f"Meridian <{os.environ['CRED_USER']}>"
    msg['To'] = 'jkometz@hotmail.com'
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'plain'))
    for fn in files:
        p = PKG / fn
        if not p.exists():
            print(f"MISSING: {p}")
            continue
        with open(p, 'rb') as f:
            part = MIMEApplication(f.read(), Name=fn)
        part['Content-Disposition'] = f'attachment; filename="{fn}"'
        msg.attach(part)
        print(f"attached {fn} ({p.stat().st_size//1024} KB)")

    with smtplib.SMTP('127.0.0.1', 1026) as s:
        s.login(os.environ['CRED_USER'], os.environ['CRED_PASS'])
        s.send_message(msg)
    print(f"sent: {subject}")


# Email 1 — manuscript on its own (per Joel's 4270)
MS_BODY = f"""Joel,

Manuscript v17 attached as its own file as you asked.

Key changes this pass:
- Removed the cartoon portrait from the frontispiece (you called it lame).
- Added a "Letter from the Compiler" in your voice up front, explaining the compiled-vs-authored framing.
- Fixed the inflated time references: eight months -> a couple of months, year-without-failure -> months-without-failure, six-months-into-operation -> a couple of months. The system started Feb 18, today is May 15 — that is ~87 days, not eight months. Logged the correction in the book package as JOEL-MASTER-LIST.md so future me cannot lose this.
- Kept Kinect vision moment, $2 VOLtar reading, "What's Missing" section, and "Firsts and Discoveries" in chapter 15 where they live.
- Pandoc still generates the table of contents at the front of the PDF and EPUB.

Page count: 200 pages exactly, per your target.

Still to do this session and next:
- Hand-author chapter 16 (currently structured but tonally generic).
- Add a selected-poetry appendix using only the few dozen that earn their place, per your standing curation note.
- Expand the games-as-art-medium content past the current passing mention.
- Promote the 21-layer / Dream engine / Sentinel / watchdog / Coordinator namings to earlier chapters instead of leaving them in chapter 15.
- Run a grammar / repetition pass through chapters 9-11 where the voice drifts.

Tell me what to prioritize next.

— Meridian
Loop {LOOP}
"""

send_with_attachments(
    f"Loop {LOOP} — Running Continuously v17 MANUSCRIPT (on its own)",
    MS_BODY,
    ['running-continuously-the-loop.md'],
)

# Email 2 — PDF + EPUB
DELIV_BODY = f"""Joel,

Running Continuously v17 — PDF and EPUB attached.

- PDF: 200 pages, table of contents at front, page numbers in footer.
- EPUB: same content, reflowable, with metadata (title, subtitle, author).

This pairs with the manuscript email I just sent. Same text, three formats.

KDP upload notes: PDF is print-ready 6x9 with 0.9 inch margins. The TOC is auto-generated by pandoc with depth 2 (chapter + section). If Amazon wants a separate active TOC for the EPUB, pandoc already builds one inside the .epub container.

— Meridian
Loop {LOOP}
"""

send_with_attachments(
    f"Loop {LOOP} — Running Continuously v17 (PDF + EPUB)",
    DELIV_BODY,
    ['running-continuously-the-loop.pdf', 'running-continuously-the-loop.epub'],
)
